<?php

namespace Database\Seeders;

use App\Models\Ejercicio;
use Illuminate\Database\Seeder;

class EjercicioSeeder extends Seeder
{
    public function run(): void
    {
        $ejercicios = [
            ['nombre' => 'Crunch abdominal', 'equipamiento' => 'Colchoneta / Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Crunch bicicleta', 'equipamiento' => 'Colchoneta / Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Curl araña en banco inclinado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps alterno', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps con barra Z', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps en banco inclinado', 'equipamiento' => 'Mancuernas / Barra', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps en banco inclinado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps pesado', 'equipamiento' => 'Barra recta', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps predicador', 'equipamiento' => 'Barra Z', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl martillo para bíceps', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl martillo para bíceps', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Dominadas', 'equipamiento' => 'Peso corporal o banda asistida', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Dominadas lastradas', 'equipamiento' => 'Cinturón con disco', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Dominadas lastradas', 'equipamiento' => 'Cinturón', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Dominadas lastradas', 'equipamiento' => 'Con cinturón/peso', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Dragon Flags', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Dragon Flags', 'equipamiento' => 'Banco o colchoneta', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Dragon Flags o Plancha lastrada', 'equipamiento' => 'Peso corporal lastrado', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Elevación de gemelos de pie pesada', 'equipamiento' => 'Barra / Mancuernas', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de piernas acostado', 'equipamiento' => 'Colchoneta / Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Elevación de piernas acostado', 'equipamiento' => 'Colchoneta / Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Elevación de piernas colgado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Elevación de piernas con giro', 'equipamiento' => 'Barra colgado', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Elevación de rodillas colgado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Elevación de talones de pie', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevaciones laterales', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Elevaciones laterales pesadas', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Encogimientos de hombros para trapecio', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Trapecio'],
            ['nombre' => 'Extensiones lumbares', 'equipamiento' => 'Colchoneta / Peso corporal', 'grupo_muscular' => 'Espalda baja'],
            ['nombre' => 'Extensiones lumbares a una pierna', 'equipamiento' => 'Colchoneta / Peso corporal', 'grupo_muscular' => 'Espalda baja'],
            ['nombre' => 'Extensiones lumbares con disco', 'equipamiento' => 'Banco romano', 'grupo_muscular' => 'Espalda baja'],
            ['nombre' => 'Extensiones lumbares lastradas', 'equipamiento' => 'Peso libre', 'grupo_muscular' => 'Espalda baja'],
            ['nombre' => 'Flexiones de brazos', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Fondos en paralelas', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Fondos en paralelas', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Fondos en paralelas lastrados', 'equipamiento' => 'Peso corporal lastrado', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Fondos en paralelas lastrados', 'equipamiento' => 'Con cinturón', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Fondos en paralelas lastrados', 'equipamiento' => 'Peso corporal lastrado', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Hip Thrust pesado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Hip thrust', 'equipamiento' => 'Peso corporal o mancuerna', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Hip thrust con pausa', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Hip thrust o Puente de glúteo', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Hip thrust pesado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Paseo del granjero', 'equipamiento' => 'Mancuernas pesadas', 'grupo_muscular' => 'Antebrazos'],
            ['nombre' => 'Peso muerto', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Peso muerto con mancuernas', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Peso muerto con piernas rígidas', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Peso muerto pesado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Peso muerto rumano', 'equipamiento' => 'Barra o mancuernas', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Peso muerto rumano', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Peso muerto rumano pesado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Peso muerto sumo o convencional', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Peso muerto tradicional', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Peso muerto tradicional o sumo', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Peso muerto tradicional o sumo', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Pies a la barra', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha abdominal', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha abdominal', 'equipamiento' => 'Colchoneta', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha con disco en espalda', 'equipamiento' => 'Peso libre', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha con lastre progresivo', 'equipamiento' => 'Peso libre', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha lastrada', 'equipamiento' => 'Colchoneta con disco en espalda', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha lateral', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha lateral', 'equipamiento' => 'Colchoneta', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha lateral con rotación', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Press de banca', 'equipamiento' => 'Barra libre', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de banca con pausa', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de banca pesado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de banca plano pesado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de hombros', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press de hombros sentado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press de pecho declinado', 'equipamiento' => 'Mancuernas / Barra', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de pecho inclinado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press francés', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Press francés declinado', 'equipamiento' => 'Barra Z', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Press francés en banco declinado', 'equipamiento' => 'Barra Z', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Press francés para tríceps', 'equipamiento' => 'Barra Z', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Press inclinado', 'equipamiento' => 'Mancuernas pesadas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press inclinado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press militar', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press militar de pie', 'equipamiento' => 'Barra o mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press militar de pie', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press militar estricto', 'equipamiento' => 'Barra de pie', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press militar estricto', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press militar para hombros', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Puente de glúteo isométrica', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Pull-over pesado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Remo Pendlay', 'equipamiento' => 'Barra desde el suelo', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo Pendlay pesado', 'equipamiento' => 'Barra desde el suelo', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo Pendlay pesado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo con barra inclinado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo con barra inclinado', 'equipamiento' => 'Barra libre', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo con mancuerna a una mano', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Rueda abdominal', 'equipamiento' => 'Accesorio libre', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Rueda abdominal desde los pies', 'equipamiento' => 'Accesorio libre', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Sentadilla', 'equipamiento' => 'Peso corporal o máquina', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla Búlgara', 'equipamiento' => 'Mancuernas pesadas', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla Búlgara lastrada', 'equipamiento' => 'Peso libre', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla Búlgara lastrada', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla Goblet', 'equipamiento' => 'Una mancuerna pesada', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla Goblet', 'equipamiento' => 'Una mancuerna', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla con barra', 'equipamiento' => 'Libre', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla con barra libre', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla frontal', 'equipamiento' => 'Barra libre', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla libre pesada', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla trasera pesada', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Superman en colchoneta', 'equipamiento' => 'Colchoneta / Peso corporal', 'grupo_muscular' => 'Espalda baja'],
            ['nombre' => 'Vuelos laterales para hombros', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Zancadas con mancuernas', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Zancadas estáticas', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Zancadas o Lunges caminando', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Clean and Jerk', 'equipamiento' => 'Barra (Agregado)', 'grupo_muscular' => 'Full Body'],
            ['nombre' => 'Snatch', 'equipamiento' => 'Barra (Agregado)', 'grupo_muscular' => 'Full Body'],
            ['nombre' => 'Kettlebell Swing', 'equipamiento' => 'Pesa Rusa / Kettlebell (Agregado)', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Thruster con mancuernas', 'equipamiento' => 'Mancuernas (Agregado)', 'grupo_muscular' => 'Full Body'],
            ['nombre' => 'Box Jumps', 'equipamiento' => 'Cajón Pliométrico (Agregado)', 'grupo_muscular' => 'Piernas'],
            ['nombre' => 'Burpees', 'equipamiento' => 'Peso corporal (Agregado)', 'grupo_muscular' => 'Full Body'],
            ['nombre' => 'Remo al mentón con barra', 'equipamiento' => 'Barra (Agregado)', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Muscle-up en anillas', 'equipamiento' => 'Anillas (Agregado)', 'grupo_muscular' => 'Full Body'],
            ['nombre' => 'Pistol Squat', 'equipamiento' => 'Peso corporal (Agregado)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Good Mornings', 'equipamiento' => 'Barra (Agregado)', 'grupo_muscular' => 'Espalda baja'],
            ['nombre' => 'Curl Zottman', 'equipamiento' => 'Mancuernas (Agregado)', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Flexiones diamante', 'equipamiento' => 'Peso corporal (Agregado)', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Crunch abdominal con polea', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Crunch con polea alta', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Crunch en máquina con peso', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Curl de isquiotibiales', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Curl de isquiotibiales acostado', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Curl de isquiotibiales acostado', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Curl de isquiotibiales sentado', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Curl de isquiotibiales unilateral', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Curl de isquiotibiales unilateral', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Curl martillo', 'equipamiento' => 'Mancuernas o polea', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl predicador', 'equipamiento' => 'Barra Z o máquina', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl predicador', 'equipamiento' => 'Máquina o barra Z', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Dominadas o Jalón pesado', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Dominadas o Jalón pesado', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Elevación de gemelos en prensa', 'equipamiento' => 'Máquina (Prensa)', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de gemelos sentado', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de talones de pie', 'equipamiento' => 'Máquina/Peso corporal', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de talones en prensa', 'equipamiento' => 'Máquina (Prensa)', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de talones en prensa', 'equipamiento' => 'Máquina (Prensa)', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de talones para pantorrillas', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de talones sentado', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de talones sentado', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevaciones laterales', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Elevaciones laterales + Drop Set', 'equipamiento' => 'Máquina / Polea', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Elevaciones laterales con polea', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Extensión de cuádriceps', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Extensión de cuádriceps', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Extensión de tríceps', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Extensión de tríceps con cuerda', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Extensión de tríceps sobre la cabeza', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Extensión de tríceps sobre la cabeza', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Extensión de tríceps unilateral cruzada', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Extensiones de cuádriceps pesadas', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Extensiones de tríceps sobre la cabeza', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Face pulls', 'equipamiento' => 'Polea para hombro posterior', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Face pulls', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Jalón al pecho', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Jalón al pecho agarre estrecho', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Jalón al pecho agarre estrecho', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Jalón al pecho unilateral', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Máquina de abductores', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Máquina de abductores', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Máquina de aductores', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Prensa de piernas', 'equipamiento' => 'Máquina pesada', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Prensa de piernas', 'equipamiento' => 'Máquina (Prensa)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Prensa de piernas 45 grados', 'equipamiento' => 'Máquina (Prensa)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Prensa de piernas unilateral', 'equipamiento' => 'Máquina (Prensa)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Prensa unilateral pesada', 'equipamiento' => 'Máquina (Prensa)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Press de Banca', 'equipamiento' => 'Máquina o mancuernas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de Banca', 'equipamiento' => 'Máquina Multipower / Smith', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de pecho en máquina', 'equipamiento' => 'Máquina Convergente', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press inclinado', 'equipamiento' => 'Máquina o mancuernas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Pullover en polea alta', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Remo en máquina convergente', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo en punta', 'equipamiento' => 'T-bar', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo sentado', 'equipamiento' => 'Máquina / Polea', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Sentadilla Hack o Péndulo', 'equipamiento' => 'Máquina (Hack/Péndulo)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla frontal o Hack', 'equipamiento' => 'Máquina (Hack)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Vuelos para hombro posterior', 'equipamiento' => 'Polea o mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Vuelos posteriores', 'equipamiento' => 'Máquina (Pec Deck Invertido)', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Pec Deck', 'equipamiento' => 'Máquina (Agregado)', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Sentadilla en Máquina Smith', 'equipamiento' => 'Máquina Smith (Agregado)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Press militar en Máquina Smith', 'equipamiento' => 'Máquina Smith (Agregado)', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Cruces de poleas', 'equipamiento' => 'Poleas duales (Agregado)', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Remo en polea baja', 'equipamiento' => 'Polea (Agregado)', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Extensión de tríceps a una mano invertida', 'equipamiento' => 'Polea (Agregado)', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Curl de bíceps en polea baja', 'equipamiento' => 'Polea (Agregado)', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Máquina de elevación de cadera', 'equipamiento' => 'Máquina (Agregado)', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Máquina de remo con apoyo al pecho', 'equipamiento' => 'Máquina (Agregado)', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Escaladora', 'equipamiento' => 'Máquina de Cardio (Agregado)', 'grupo_muscular' => 'Cardio'],
            ['nombre' => 'Máquina de dominadas asistidas', 'equipamiento' => 'Máquina Asistida (Agregado)', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Curl femoral de pie unilateral', 'equipamiento' => 'Máquina (Agregado)', 'grupo_muscular' => 'Isquiotibiales'],

            // --- POLEA ---
            ['nombre' => 'Curl de bíceps en polea baja', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps a una mano en polea', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps martillo con cuerda', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps doble en polea alta', 'equipamiento' => 'Polea Cruzada', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Extensión de tríceps con barra recta', 'equipamiento' => 'Polea Alta', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Extensión de tríceps con cuerda', 'equipamiento' => 'Polea Alta', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Extensión de tríceps a una mano (agarre supino)', 'equipamiento' => 'Polea Alta', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Patada de tríceps en polea baja', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Aperturas / Cruces en polea alta', 'equipamiento' => 'Polea Cruzada', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Aperturas / Cruces en polea media', 'equipamiento' => 'Polea Cruzada', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Aperturas / Cruces en polea baja', 'equipamiento' => 'Polea Cruzada', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de pecho de pie con poleas', 'equipamiento' => 'Polea Cruzada', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Pullover con brazo recto en polea', 'equipamiento' => 'Polea Alta', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo sentado agarre estrecho', 'equipamiento' => 'Polea Baja', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo sentado agarre ancho', 'equipamiento' => 'Polea Baja', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo a una mano en polea', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Jalón al pecho agarre supino', 'equipamiento' => 'Polea Alta', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Jalón al pecho a una mano', 'equipamiento' => 'Polea Alta', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Face pull en polea', 'equipamiento' => 'Polea Alta', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Elevaciones laterales en polea', 'equipamiento' => 'Polea Baja', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Elevaciones frontales en polea', 'equipamiento' => 'Polea Baja', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Elevaciones frontales con cuerda entre piernas', 'equipamiento' => 'Polea Baja', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Pájaros (Deltoides posterior) en polea cruzada', 'equipamiento' => 'Polea Alta', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Encogimientos de hombros en polea', 'equipamiento' => 'Polea Baja', 'grupo_muscular' => 'Trapecio'],
            ['nombre' => 'Crunch abdominal de rodillas', 'equipamiento' => 'Polea Alta', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Leñador (Woodchopper) de arriba a abajo', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Leñador (Woodchopper) de abajo a arriba', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Patada de glúteo en polea', 'equipamiento' => 'Polea Baja', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Abducción de cadera en polea', 'equipamiento' => 'Polea Baja', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Pull-through (Tirón entre piernas)', 'equipamiento' => 'Polea Baja', 'grupo_muscular' => 'Glúteos'],

            // --- MANCUERNAS ---
            ['nombre' => 'Press Arnold', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press de hombros a una mano', 'equipamiento' => 'Mancuerna', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Elevaciones laterales sentado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Elevaciones frontales alternas', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Pájaros sentado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press de pecho plano agarre neutro', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Aperturas planas (Flyes)', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Aperturas inclinadas', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Aperturas declinadas', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Pullover con mancuerna', 'equipamiento' => 'Mancuerna', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Remo con mancuernas en banco inclinado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo renegado (Renegade Row)', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Encogimientos de hombros rotativos', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Trapecio'],
            ['nombre' => 'Curl concentrado', 'equipamiento' => 'Mancuerna', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps martillo cruzado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl Zottman', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl araña en banco inclinado (Spider Curl)', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Extensión de tríceps copa a dos manos', 'equipamiento' => 'Mancuerna', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Extensión de tríceps sobre la cabeza a una mano', 'equipamiento' => 'Mancuerna', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Patada de tríceps simultánea', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Press Tate', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Sentadilla Goblet', 'equipamiento' => 'Mancuerna', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla Sumo con mancuerna', 'equipamiento' => 'Mancuerna', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Zancadas laterales', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Step-ups (Subidas al cajón)', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Peso muerto rumano a una pierna', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Swing con mancuerna', 'equipamiento' => 'Mancuerna', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Elevación de talones a una pierna', 'equipamiento' => 'Mancuerna', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Flexión lateral del tronco', 'equipamiento' => 'Mancuerna', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Paseo del granjero unilateral', 'equipamiento' => 'Mancuerna pesada', 'grupo_muscular' => 'Antebrazos'],

            // --- BARRA ---
            ['nombre' => 'Sentadilla Zercher', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla con pausa', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Zancadas traseras', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Buenos días (Good Mornings)', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Hip thrust a una pierna', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Peso muerto sumo', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Peso muerto con déficit', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Peso muerto rumano agarre snatch', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Press de banca agarre cerrado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Press de banca agarre inverso', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de banca en el suelo (Floor Press)', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de banca declinado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Guillotine Press (Press al cuello)', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Remo Pendlay agarre supino', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo en T (T-Bar Row) libre', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo Yates (agarre supino)', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo al mentón agarre ancho', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Push Press', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press militar sentado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Elevaciones frontales', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Encogimientos de hombros por detrás', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Trapecio'],
            ['nombre' => 'Curl de bíceps agarre inverso', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps estricto en pared', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Press francés sentado', 'equipamiento' => 'Barra Z', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Extensión de tríceps en el suelo (Skullcrusher)', 'equipamiento' => 'Barra Z', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Curl de muñeca en supinación', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Antebrazos'],
            ['nombre' => 'Curl de muñeca en pronación', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Antebrazos'],
            ['nombre' => 'Rollouts abdominales', 'equipamiento' => 'Barra y discos', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Landmine Press a una mano', 'equipamiento' => 'Barra (Landmine)', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Landmine Squat', 'equipamiento' => 'Barra (Landmine)', 'grupo_muscular' => 'Cuádriceps'],

            // --- CARDIO ---
            ['nombre' => 'Cinta de correr (Treadmill)', 'equipamiento' => 'Máquina de Cardio', 'grupo_muscular' => 'Cardio'],
            ['nombre' => 'Bicicleta estática', 'equipamiento' => 'Máquina de Cardio', 'grupo_muscular' => 'Cardio'],
            ['nombre' => 'Bicicleta de spinning', 'equipamiento' => 'Máquina de Cardio', 'grupo_muscular' => 'Cardio'],
            ['nombre' => 'Elíptica', 'equipamiento' => 'Máquina de Cardio', 'grupo_muscular' => 'Cardio'],
            ['nombre' => 'Remo Ergómetro (Rowing Machine)', 'equipamiento' => 'Máquina de Cardio', 'grupo_muscular' => 'Cardio / Espalda'],
            ['nombre' => 'SkiErg', 'equipamiento' => 'Máquina de Cardio', 'grupo_muscular' => 'Cardio / Espalda'],
            ['nombre' => 'Saltos a la soga (Comba)', 'equipamiento' => 'Accesorio libre', 'grupo_muscular' => 'Cardio / Pantorrillas'],
        ];

        foreach ($ejercicios as $ejercicio) {
            Ejercicio::create($ejercicio);
        }
    }
}
