<?php

namespace Database\Seeders;

use App\Models\Ejercicio;
use Illuminate\Database\Seeder;

class EjercicioSeeder extends Seeder
{
    public function run(): void
    {
        $ejercicios = [
            ['nombre' => 'Crunch abdominal', 'equipamiento' => 'Colchoneta / Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Crunch bicicleta', 'equipamiento' => 'Colchoneta / Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Curl araña en banco inclinado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps alterno', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps con barra Z', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps en banco inclinado', 'equipamiento' => 'Mancuernas / Barra', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps en banco inclinado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps pesado', 'equipamiento' => 'Barra recta', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl de bíceps predicador', 'equipamiento' => 'Barra Z', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl martillo para bíceps', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl martillo para bíceps', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Dominadas', 'equipamiento' => 'Peso corporal o banda asistida', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Dominadas lastradas', 'equipamiento' => 'Cinturón con disco', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Dominadas lastradas', 'equipamiento' => 'Cinturón', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Dominadas lastradas', 'equipamiento' => 'Con cinturón/peso', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Dragon Flags', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Dragon Flags', 'equipamiento' => 'Banco o colchoneta', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Dragon Flags o Plancha lastrada', 'equipamiento' => 'Peso corporal lastrado', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Elevación de gemelos de pie pesada', 'equipamiento' => 'Barra / Mancuernas', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de piernas acostado', 'equipamiento' => 'Colchoneta / Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Elevación de piernas acostado', 'equipamiento' => 'Colchoneta / Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Elevación de piernas colgado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Elevación de piernas con giro', 'equipamiento' => 'Barra colgado', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Elevación de rodillas colgado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Elevación de talones de pie', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevaciones laterales', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Elevaciones laterales pesadas', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Encogimientos de hombros para trapecio', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Trapecio'],
            ['nombre' => 'Extensiones lumbares', 'equipamiento' => 'Colchoneta / Peso corporal', 'grupo_muscular' => 'Espalda baja'],
            ['nombre' => 'Extensiones lumbares a una pierna', 'equipamiento' => 'Colchoneta / Peso corporal', 'grupo_muscular' => 'Espalda baja'],
            ['nombre' => 'Extensiones lumbares con disco', 'equipamiento' => 'Banco romano', 'grupo_muscular' => 'Espalda baja'],
            ['nombre' => 'Extensiones lumbares lastradas', 'equipamiento' => 'Peso libre', 'grupo_muscular' => 'Espalda baja'],
            ['nombre' => 'Flexiones de brazos', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Fondos en paralelas', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Fondos en paralelas', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Fondos en paralelas lastrados', 'equipamiento' => 'Peso corporal lastrado', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Fondos en paralelas lastrados', 'equipamiento' => 'Con cinturón', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Fondos en paralelas lastrados', 'equipamiento' => 'Peso corporal lastrado', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Hip Thrust pesado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Hip thrust', 'equipamiento' => 'Peso corporal o mancuerna', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Hip thrust con pausa', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Hip thrust o Puente de glúteo', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Hip thrust pesado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Paseo del granjero', 'equipamiento' => 'Mancuernas pesadas', 'grupo_muscular' => 'Antebrazos'],
            ['nombre' => 'Peso muerto', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Peso muerto con mancuernas', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Peso muerto con piernas rígidas', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Peso muerto pesado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Peso muerto rumano', 'equipamiento' => 'Barra o mancuernas', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Peso muerto rumano', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Peso muerto rumano pesado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Peso muerto sumo o convencional', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Peso muerto tradicional', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Peso muerto tradicional o sumo', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Peso muerto tradicional o sumo', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Pies a la barra', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha abdominal', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha abdominal', 'equipamiento' => 'Colchoneta', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha con disco en espalda', 'equipamiento' => 'Peso libre', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha con lastre progresivo', 'equipamiento' => 'Peso libre', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha lastrada', 'equipamiento' => 'Colchoneta con disco en espalda', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha lateral', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha lateral', 'equipamiento' => 'Colchoneta', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Plancha lateral con rotación', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Press de banca', 'equipamiento' => 'Barra libre', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de banca con pausa', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de banca pesado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de banca plano pesado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de hombros', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press de hombros sentado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press de pecho declinado', 'equipamiento' => 'Mancuernas / Barra', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de pecho inclinado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press francés', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Press francés declinado', 'equipamiento' => 'Barra Z', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Press francés en banco declinado', 'equipamiento' => 'Barra Z', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Press francés para tríceps', 'equipamiento' => 'Barra Z', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Press inclinado', 'equipamiento' => 'Mancuernas pesadas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press inclinado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press militar', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press militar de pie', 'equipamiento' => 'Barra o mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press militar de pie', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press militar estricto', 'equipamiento' => 'Barra de pie', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press militar estricto', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Press militar para hombros', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Puente de glúteo isométrica', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Pull-over pesado', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Remo Pendlay', 'equipamiento' => 'Barra desde el suelo', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo Pendlay pesado', 'equipamiento' => 'Barra desde el suelo', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo Pendlay pesado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo con barra inclinado', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo con barra inclinado', 'equipamiento' => 'Barra libre', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo con mancuerna a una mano', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Rueda abdominal', 'equipamiento' => 'Accesorio libre', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Rueda abdominal desde los pies', 'equipamiento' => 'Accesorio libre', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Sentadilla', 'equipamiento' => 'Peso corporal o máquina', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla Búlgara', 'equipamiento' => 'Mancuernas pesadas', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla Búlgara lastrada', 'equipamiento' => 'Peso libre', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla Búlgara lastrada', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla Goblet', 'equipamiento' => 'Una mancuerna pesada', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla Goblet', 'equipamiento' => 'Una mancuerna', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla con barra', 'equipamiento' => 'Libre', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla con barra libre', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla frontal', 'equipamiento' => 'Barra libre', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla libre pesada', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla trasera pesada', 'equipamiento' => 'Barra', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Superman en colchoneta', 'equipamiento' => 'Colchoneta / Peso corporal', 'grupo_muscular' => 'Espalda baja'],
            ['nombre' => 'Vuelos laterales para hombros', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Zancadas con mancuernas', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Zancadas estáticas', 'equipamiento' => 'Peso corporal', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Zancadas o Lunges caminando', 'equipamiento' => 'Mancuernas', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Clean and Jerk', 'equipamiento' => 'Barra (Agregado)', 'grupo_muscular' => 'Full Body'],
            ['nombre' => 'Snatch', 'equipamiento' => 'Barra (Agregado)', 'grupo_muscular' => 'Full Body'],
            ['nombre' => 'Kettlebell Swing', 'equipamiento' => 'Pesa Rusa / Kettlebell (Agregado)', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Thruster con mancuernas', 'equipamiento' => 'Mancuernas (Agregado)', 'grupo_muscular' => 'Full Body'],
            ['nombre' => 'Box Jumps', 'equipamiento' => 'Cajón Pliométrico (Agregado)', 'grupo_muscular' => 'Piernas'],
            ['nombre' => 'Burpees', 'equipamiento' => 'Peso corporal (Agregado)', 'grupo_muscular' => 'Full Body'],
            ['nombre' => 'Remo al mentón con barra', 'equipamiento' => 'Barra (Agregado)', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Muscle-up en anillas', 'equipamiento' => 'Anillas (Agregado)', 'grupo_muscular' => 'Full Body'],
            ['nombre' => 'Pistol Squat', 'equipamiento' => 'Peso corporal (Agregado)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Good Mornings', 'equipamiento' => 'Barra (Agregado)', 'grupo_muscular' => 'Espalda baja'],
            ['nombre' => 'Curl Zottman', 'equipamiento' => 'Mancuernas (Agregado)', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Flexiones diamante', 'equipamiento' => 'Peso corporal (Agregado)', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Crunch abdominal con polea', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Crunch con polea alta', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Crunch en máquina con peso', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Abdomen'],
            ['nombre' => 'Curl de isquiotibiales', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Curl de isquiotibiales acostado', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Curl de isquiotibiales acostado', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Curl de isquiotibiales sentado', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Curl de isquiotibiales unilateral', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Curl de isquiotibiales unilateral', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Isquiotibiales'],
            ['nombre' => 'Curl martillo', 'equipamiento' => 'Mancuernas o polea', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl predicador', 'equipamiento' => 'Barra Z o máquina', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Curl predicador', 'equipamiento' => 'Máquina o barra Z', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Dominadas o Jalón pesado', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Dominadas o Jalón pesado', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Elevación de gemelos en prensa', 'equipamiento' => 'Máquina (Prensa)', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de gemelos sentado', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de talones de pie', 'equipamiento' => 'Máquina/Peso corporal', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de talones en prensa', 'equipamiento' => 'Máquina (Prensa)', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de talones en prensa', 'equipamiento' => 'Máquina (Prensa)', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de talones para pantorrillas', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de talones sentado', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevación de talones sentado', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Pantorrillas'],
            ['nombre' => 'Elevaciones laterales', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Elevaciones laterales + Drop Set', 'equipamiento' => 'Máquina / Polea', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Elevaciones laterales con polea', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Extensión de cuádriceps', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Extensión de cuádriceps', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Extensión de tríceps', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Extensión de tríceps con cuerda', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Extensión de tríceps sobre la cabeza', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Extensión de tríceps sobre la cabeza', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Extensión de tríceps unilateral cruzada', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Extensiones de cuádriceps pesadas', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Extensiones de tríceps sobre la cabeza', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Face pulls', 'equipamiento' => 'Polea para hombro posterior', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Face pulls', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Jalón al pecho', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Jalón al pecho agarre estrecho', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Jalón al pecho agarre estrecho', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Jalón al pecho unilateral', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Máquina de abductores', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Máquina de abductores', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Máquina de aductores', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Prensa de piernas', 'equipamiento' => 'Máquina pesada', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Prensa de piernas', 'equipamiento' => 'Máquina (Prensa)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Prensa de piernas 45 grados', 'equipamiento' => 'Máquina (Prensa)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Prensa de piernas unilateral', 'equipamiento' => 'Máquina (Prensa)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Prensa unilateral pesada', 'equipamiento' => 'Máquina (Prensa)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Press de Banca', 'equipamiento' => 'Máquina o mancuernas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de Banca', 'equipamiento' => 'Máquina Multipower / Smith', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press de pecho en máquina', 'equipamiento' => 'Máquina Convergente', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Press inclinado', 'equipamiento' => 'Máquina o mancuernas', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Pullover en polea alta', 'equipamiento' => 'Polea', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Remo en máquina convergente', 'equipamiento' => 'Máquina', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo en punta', 'equipamiento' => 'T-bar', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Remo sentado', 'equipamiento' => 'Máquina / Polea', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Sentadilla Hack o Péndulo', 'equipamiento' => 'Máquina (Hack/Péndulo)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Sentadilla frontal o Hack', 'equipamiento' => 'Máquina (Hack)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Vuelos para hombro posterior', 'equipamiento' => 'Polea o mancuernas', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Vuelos posteriores', 'equipamiento' => 'Máquina (Pec Deck Invertido)', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Pec Deck', 'equipamiento' => 'Máquina (Agregado)', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Sentadilla en Máquina Smith', 'equipamiento' => 'Máquina Smith (Agregado)', 'grupo_muscular' => 'Cuádriceps'],
            ['nombre' => 'Press militar en Máquina Smith', 'equipamiento' => 'Máquina Smith (Agregado)', 'grupo_muscular' => 'Hombros'],
            ['nombre' => 'Cruces de poleas', 'equipamiento' => 'Poleas duales (Agregado)', 'grupo_muscular' => 'Pecho'],
            ['nombre' => 'Remo en polea baja', 'equipamiento' => 'Polea (Agregado)', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Extensión de tríceps a una mano invertida', 'equipamiento' => 'Polea (Agregado)', 'grupo_muscular' => 'Tríceps'],
            ['nombre' => 'Curl de bíceps en polea baja', 'equipamiento' => 'Polea (Agregado)', 'grupo_muscular' => 'Bíceps'],
            ['nombre' => 'Máquina de elevación de cadera', 'equipamiento' => 'Máquina (Agregado)', 'grupo_muscular' => 'Glúteos'],
            ['nombre' => 'Máquina de remo con apoyo al pecho', 'equipamiento' => 'Máquina (Agregado)', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Escaladora', 'equipamiento' => 'Máquina de Cardio (Agregado)', 'grupo_muscular' => 'Cardio'],
            ['nombre' => 'Máquina de dominadas asistidas', 'equipamiento' => 'Máquina Asistida (Agregado)', 'grupo_muscular' => 'Espalda'],
            ['nombre' => 'Curl femoral de pie unilateral', 'equipamiento' => 'Máquina (Agregado)', 'grupo_muscular' => 'Isquiotibiales'],
        ];

        foreach ($ejercicios as $ejercicio) {
            Ejercicio::create($ejercicio);
        }
    }
}
