<?php

namespace Database\Seeders;

use App\Models\Rutina;
use Illuminate\Database\Seeder;

class RutinaSeeder extends Seeder
{
    public function run(): void
    {
        $rutinas = [
            // PRINCIPIANTE 2 DÍAS
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Sentadilla'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press de Banca'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Remo sentado'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press de hombros'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de bíceps'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensión de tríceps'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '12', 'reps_max' => '20', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de talones para pantorrillas'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => 'N/A (30 seg)', 'reps_max' => 'N/A (60 seg)', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Plancha abdominal'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Peso muerto'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Prensa de piernas'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Jalón al pecho'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '5', 'reps_max' => '15', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Flexiones de brazos'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Vuelos laterales para hombros'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de isquiotibiales'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensiones lumbares'],
            ['nivel' => 'Principiante', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '15', 'reps_max' => '20', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Crunch abdominal'],

            // INTERMEDIO 2 DÍAS
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Sentadilla con barra libre'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Press de banca'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Dominadas'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press militar para hombros'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Peso muerto rumano'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de bíceps con barra Z'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Press francés para tríceps'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de piernas colgado'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '6', 'reps_max' => '8', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Peso muerto tradicional'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Prensa de piernas'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Remo con barra inclinado'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press de pecho inclinado'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevaciones laterales con polea'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl martillo para bíceps'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensión de tríceps con cuerda'],
            ['nivel' => 'Intermedio', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Rueda abdominal'],

            // AVANZADO 2 DÍAS
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '5', 'reps_max' => '8', 'descanso_min' => 2.5, 'ejercicio_nombre' => 'Sentadilla frontal'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '5', 'reps_max' => '8', 'descanso_min' => 2.5, 'ejercicio_nombre' => 'Press de banca con pausa'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '6', 'reps_max' => '8', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Dominadas lastradas'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '6', 'reps_max' => '8', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Press militar estricto'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Hip Thrust pesado'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de bíceps en banco inclinado'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Fondos en paralelas lastrados'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Pies a la barra'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '3', 'reps_max' => '5', 'descanso_min' => 3.0, 'ejercicio_nombre' => 'Peso muerto sumo o convencional'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Sentadilla Búlgara'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '6', 'reps_max' => '8', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Remo Pendlay'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Press de pecho declinado'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Face pulls'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl predicador'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensiones de tríceps sobre la cabeza'],
            ['nivel' => 'Avanzado', 'modalidad' => '2 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Dragon Flags o Plancha lastrada'],

            // PRINCIPIANTE 3 DÍAS
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press de pecho en máquina'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press inclinado'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press de hombros sentado'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevaciones laterales'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensión de tríceps'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Press francés con mancuernas'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '15', 'reps_max' => '20', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Crunch abdominal'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => 'N/A (30 seg)', 'reps_max' => 'N/A (60 seg)', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Plancha abdominal'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Jalón al pecho'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Remo sentado'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Remo con mancuerna a una mano'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Pullover en polea alta'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de bíceps alterno'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl martillo'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensiones lumbares'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '15', 'reps_max' => '20', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de piernas acostado'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Prensa de piernas'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Sentadilla Goblet'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensión de cuádriceps'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de isquiotibiales'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Hip thrust'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Máquina de abductores'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '15', 'reps_max' => '20', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de talones de pie'],
            ['nivel' => 'Principiante', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => 'N/A (30 seg)', 'reps_max' => 'N/A (45 seg)', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Plancha lateral'],

            // INTERMEDIO 3 DÍAS
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Press de banca'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Press militar de pie'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press de pecho inclinado'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevaciones laterales'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Fondos en paralelas'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensión de tríceps sobre la cabeza'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de rodillas colgado'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Crunch abdominal con polea'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '6', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Dominadas'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Remo con barra inclinado'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Jalón al pecho agarre estrecho'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Face pulls'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Curl de bíceps con barra Z'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de bíceps en banco inclinado'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Encogimientos de hombros para trapecio'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensiones lumbares con disco'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Sentadilla con barra'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Peso muerto rumano'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Prensa de piernas unilateral'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Zancadas con mancuernas'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de isquiotibiales acostado'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '15', 'reps_max' => '20', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de talones sentado'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de talones en prensa'],
            ['nivel' => 'Intermedio', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Rueda abdominal'],

            // AVANZADO 3 DÍAS
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '5', 'reps_max' => '8', 'descanso_min' => 2.5, 'ejercicio_nombre' => 'Press de banca plano pesado'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '5', 'reps_max' => '8', 'descanso_min' => 2.5, 'ejercicio_nombre' => 'Press militar estricto'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Fondos en paralelas lastrados'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Elevaciones laterales pesadas'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press francés en banco declinado'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensión de tríceps unilateral cruzada'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Dragon Flags'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de piernas con giro'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '3', 'reps_max' => '5', 'descanso_min' => 3.0, 'ejercicio_nombre' => 'Peso muerto tradicional o sumo'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '5', 'reps_max' => '8', 'descanso_min' => 2.5, 'ejercicio_nombre' => 'Dominadas lastradas'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '6', 'reps_max' => '8', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Remo Pendlay pesado'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Pull-over pesado'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Vuelos para hombro posterior'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Curl de bíceps predicador'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl araña en banco inclinado'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => 'N/A (45 seg)', 'reps_max' => 'N/A (60 seg)', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Paseo del granjero'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '5', 'reps_max' => '8', 'descanso_min' => 3.0, 'ejercicio_nombre' => 'Sentadilla libre pesada'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Sentadilla Búlgara lastrada'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '6', 'reps_max' => '8', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Hip Thrust pesado'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Peso muerto con piernas rígidas'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensiones de cuádriceps pesadas'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de isquiotibiales unilateral'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de gemelos en prensa'],
            ['nivel' => 'Avanzado', 'modalidad' => '3 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => 'N/A (45 seg)', 'reps_max' => 'N/A (60 seg)', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Plancha lastrada'],

            // PRINCIPIANTE 4 DÍAS
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press de pecho en máquina'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Jalón al pecho'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press de hombros'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Remo sentado'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de bíceps alterno'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensión de tríceps'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '15', 'reps_max' => '20', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Crunch abdominal'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => 'N/A (30 seg)', 'reps_max' => 'N/A (60 seg)', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Plancha abdominal'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Prensa de piernas'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Peso muerto con mancuernas'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensión de cuádriceps'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de isquiotibiales'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '15', 'reps_max' => '20', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de talones de pie'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Máquina de abductores'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensiones lumbares'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => 'N/A (30 seg)', 'reps_max' => 'N/A (45 seg)', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Plancha lateral'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press inclinado'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Remo con mancuerna a una mano'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevaciones laterales'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Pullover en polea alta'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl martillo para bíceps'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Press francés con mancuernas'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '15', 'reps_max' => '20', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de piernas acostado'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => 'N/A (30 seg)', 'reps_max' => 'N/A (60 seg)', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Puente de glúteo isométrica'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Sentadilla Goblet'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Hip thrust'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Zancadas estáticas'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de isquiotibiales sentado'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '15', 'reps_max' => '20', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de talones sentado'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Máquina de aductores'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '15', 'reps_max' => '20', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Crunch bicicleta'],
            ['nivel' => 'Principiante', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Superman en colchoneta'],

            // INTERMEDIO 4 DÍAS
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Press de banca'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Dominadas o Jalón pesado'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press militar'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Remo con barra inclinado'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de bíceps con barra Z'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Fondos en paralelas'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Face pulls'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Rueda abdominal'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Sentadilla con barra'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Peso muerto rumano'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Prensa de piernas 45 grados'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de isquiotibiales acostado'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de talones en prensa'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Zancadas con mancuernas'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de piernas colgado'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => 'N/A (45 seg)', 'reps_max' => 'N/A (60 seg)', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Plancha con disco en espalda'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press inclinado'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Remo en punta'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Press militar de pie'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Jalón al pecho agarre estrecho'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevaciones laterales con polea'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de bíceps en banco inclinado'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensión de tríceps sobre la cabeza'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Crunch con polea alta'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 4, 'reps_min' => '6', 'reps_max' => '8', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Peso muerto tradicional o sumo'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Sentadilla frontal o Hack'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Hip thrust pesado'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensión de cuádriceps'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de isquiotibiales sentado'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 4, 'reps_min' => '15', 'reps_max' => '20', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de talones sentado'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensiones lumbares lastradas'],
            ['nivel' => 'Intermedio', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '10 (por lado)', 'reps_max' => '15 (por lado)', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Plancha lateral con rotación'],

            // AVANZADO 4 DÍAS
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '3', 'reps_max' => '5', 'descanso_min' => 3.0, 'ejercicio_nombre' => 'Press de banca pesado'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '5', 'reps_max' => '8', 'descanso_min' => 2.5, 'ejercicio_nombre' => 'Remo Pendlay pesado'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '5', 'reps_max' => '8', 'descanso_min' => 2.5, 'ejercicio_nombre' => 'Press militar estricto'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 4, 'reps_min' => '5', 'reps_max' => '8', 'descanso_min' => 2.5, 'ejercicio_nombre' => 'Dominadas lastradas'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Fondos en paralelas lastrados'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Curl de bíceps pesado'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Dragon Flags'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 1', 'series' => 3, 'reps_min' => 'N/A (45 seg)', 'reps_max' => 'N/A (60 seg)', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Paseo del granjero'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '3', 'reps_max' => '5', 'descanso_min' => 3.0, 'ejercicio_nombre' => 'Sentadilla trasera pesada'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '3', 'reps_max' => '5', 'descanso_min' => 3.0, 'ejercicio_nombre' => 'Peso muerto pesado'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Prensa unilateral pesada'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Peso muerto rumano pesado'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Elevación de gemelos de pie pesada'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Curl de isquiotibiales unilateral'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Pies a la barra'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 2', 'series' => 3, 'reps_min' => '5', 'reps_max' => '8', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Rueda abdominal desde los pies'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Press inclinado'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Jalón al pecho unilateral'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Elevaciones laterales + Drop Set'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Remo en máquina convergente'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Press francés declinado'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 4, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Curl predicador'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Vuelos posteriores'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 3', 'series' => 3, 'reps_min' => '10', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Crunch en máquina con peso'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Sentadilla Hack o Péndulo'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 4, 'reps_min' => '8', 'reps_max' => '10', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Sentadilla Búlgara lastrada'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 4, 'reps_min' => '8', 'reps_max' => '12', 'descanso_min' => 2.0, 'ejercicio_nombre' => 'Hip thrust con pausa'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 4, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensiones de cuádriceps'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 4, 'reps_min' => '12', 'reps_max' => '15', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Curl de isquiotibiales acostado'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 4, 'reps_min' => '15', 'reps_max' => '20', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Elevación de gemelos sentado'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => '10', 'reps_max' => '12', 'descanso_min' => 1.0, 'ejercicio_nombre' => 'Extensiones lumbares a una pierna'],
            ['nivel' => 'Avanzado', 'modalidad' => '4 Días', 'dia' => 'Día 4', 'series' => 3, 'reps_min' => 'N/A (45 seg)', 'reps_max' => 'N/A (60 seg)', 'descanso_min' => 1.5, 'ejercicio_nombre' => 'Plancha con lastre progresivo'],
        ];

        foreach ($rutinas as $rutina) {
            Rutina::create($rutina);
        }
    }
}
